# Generated by Django 5.0.3 on 2024-03-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="color_bg",
            field=models.CharField(default="#f9ea97", max_length=7),
        ),
        migrations.AddField(
            model_name="note",
            name="view_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
