# Generated by Django 5.0.3 on 2024-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_note_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("NOTES", "notes"), ("CHECKLIST", "checklist")],
                default="NOTES",
                max_length=255,
                null=True,
            ),
        ),
    ]
